name: Build Linux gcc+gfortran
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      FC: gfortran-9
      CC: gcc-9
      CXX: g++-9

    steps:

    - name: Install-mpi
      run: |
        sudo apt-get install libmpich-dev

    - name: Checkout
      uses: actions/checkout@v2

    - name: Init submodules
      run: git submodule update --init --recursive

    - name: Build NCEPLIBS-external
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=install -DBUILD_MPI=OFF
        make -j4
        cat install/share/nceplibs-external.cmake.config
